version: "3.9"

services:
  api:
    build: .
    container_name: locations_api
    env_file:
      - .env
    environment:
      API_MAPBOX_DATABASE_URL: postgresql+asyncpg://postgres:postgres@db:5432/locations
      API_MAPBOX_APP_NAME: locations-service
      API_MAPBOX_DEBUG: "true"
    depends_on:
      - db
    ports:
      - "8000:8000"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./:/app

  db:
    image: postgres:15-alpine
    container_name: locations_db
    environment:
      POSTGRES_DB: locations
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  adminer:
    image: adminer:4
    container_name: locations_adminer
    restart: always
    depends_on:
      - db
    ports:
      - "8080:8080"

volumes:
  pg_data:
