services:
  backend:
    build: .
    container_name: location_api
    ports:
      - "8003:8000"
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - pg-docker_default

networks:
  pg-docker_default:
    external: true