services:
  location_api:
    build: .
    container_name: location_api
    expose:
      - "8000"
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - pg-docker_default

networks:
  pg-docker_default:
    external: true
